In [1]:
import pandas as pd

In [6]:
data = pd.read_csv(r"C:\Users\yash mohite\OneDrive\Desktop\netflix recommendation system\netflix_titles.csv")

In [7]:
data.to_csv("movie_series",index=False)

In [8]:
data = pd.read_csv("movie_series")

In [9]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [10]:
data.tail()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [14]:
list(data.columns)

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description']

In [15]:
data.dtypes

show_id         object
type            object
title           object
director        object
cast            object
country         object
date_added      object
release_year     int64
rating          object
duration        object
listed_in       object
description     object
dtype: object

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

In [19]:
data.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

In [26]:
data[data.dtypes[data.dtypes == "object"].index].describe()

,show_id,type,title,director,cast,country,date_added,rating,duration,listed_in,description
count,8807,8807,8807,6173,7982,7976,8797,8803,8804,8807,8807
unique,8807,2,8807,4528,7692,748,1767,17,220,514,8775
top,s1,Movie,Dick Johnson Is Dead,Rajiv Chilaka,David Attenborough,United States,"January 1, 2020",TV-MA,1 Season,"Dramas, International Movies","Paranormal activity at a lush, abandoned prope..."
freq,1,6131,1,19,19,2818,109,3207,1793,362,4

In [27]:
data.head(4)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."

In [30]:
# how many movie are there in this data set
len(data[data["type"] == "Movie"])

6131

In [34]:
# how many Tv.series are there in this data set
len(data[data["type"] == "TV Show"])

2676

In [41]:
# How many movies from USA
len(data[(data["type"] == "Movie") & (data["country"] == "United States")])

2058

In [42]:
# How many movies from india
len(data[(data["type"] == "Movie") & (data["country"] == "India")])

893

In [44]:
# How many movies from india china
len(data[(data["type"] == "Movie") & (data["country"] == "China")])

28

In [45]:
# How many movies from india japan
len(data[(data["type"] == "Movie") & (data["country"] == "Japan")])

76

In [49]:
# How many series from USA
len(data[(data["type"] == "TV Show") & (data["country"] == "United States")])

760

In [50]:
# How many series from India
len(data[(data["type"] == "TV Show") & (data["country"] == "India")])

79

In [53]:
# How many series from japan
len(data[(data["type"] == "TV Show") & (data["country"] == "Japan")])

169

In [57]:
# how many movies relesed in 2018
len(data[(data["type"] == "Movie") & (data["release_year"] == 2018)])

767

In [58]:
# how many movies relesed in 2019
len(data[(data["type"] == "Movie") & (data["release_year"] == 2019)])

633

In [59]:
# how many movies relesed in 2020
len(data[(data["type"] == "Movie") & (data["release_year"] == 2020)])

517

In [72]:
# how many series relesed in 2018
len(data[(data["type"] == "TV Show") & (data["release_year"] == 2018)])

380

In [73]:
# how many series relesed in 2019
len(data[(data["type"] == "TV Show") & (data["release_year"] == 2019)])

397

In [75]:
# how many series relesed in 2020
len(data[(data["type"] == "TV Show") & (data["release_year"] == 2020)])

436

In [78]:
# how many series relesed in 2021
len(data[(data["type"] == "TV Show") & (data["release_year"] == 2021)])

315

In [69]:
# how many movie are relased in japan in 2020
len(data[(data["type"] == "Movie") & (data["release_year"] == 2020) & (data["country"] == "Japan")])

7

In [81]:
# how many Series are relased in japan in 2020
len(data[(data["type"] == "TV Show") & (data["release_year"] == 2020) & (data["country"] == "Japan")])

13

In [82]:
# how many series are relesed in india in 2020
len(data[(data["type"] == "TV Show") & (data["release_year"] == 2020) & (data["country"] == "India")])

16

In [83]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [87]:
# how many movies are pg-13 
len(data[(data["type"] == "Movie") & (data["rating"] == "PG-13")])

490

In [88]:
# how many movies are R-Rated
len(data[(data["type"] == "Movie") & (data["rating"] == "R")])

797

In [91]:
# how many series sare Rrated 
data[(data["type"] == "TV Show") & (data["rating"] == "R")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
3893,s3894,TV Show,The Hateful Eight: Extended Version,Quentin Tarantino,"Samuel L. Jackson, Kurt Russell, Jennifer Jaso...",NaN,"April 25, 2019",2015,R,1 Season,TV Shows,Trapped at a stagecoach stop as a storm rages ...
7593,s7594,TV Show,Nobel,NaN,"Aksel Hennie, Tuva Novotny, Anders Danielsen L...",Norway,"December 10, 2016",2016,R,1 Season,"International TV Shows, TV Dramas, TV Thrillers",A series of incidents in Afghanistan set compl...

In [ ]:
# fetch the documentry movies and ratings

In [93]:
data[(data["type"] == "Movie") & (data["rating"] == "R") & (data["listed_in"] == "Documentaries")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1195,s1196,Movie,Operation Varsity Blues: The College Admission...,Chris Smith,Matthew Modine,United States,"March 17, 2021",2021,R,100 min,Documentaries,Reenactments drive this documentary investigat...
1343,s1344,Movie,"Strip Down, Rise Up",Michèle Ohayon,NaN,United States,"February 5, 2021",2021,R,113 min,Documentaries,In an effort to reclaim their bodies and lives...
1690,s1691,Movie,Whose Streets?,"Sabaah Folayan, Damon Davis",NaN,United States,"November 16, 2020",2017,R,102 min,Documentaries,"Powered by activists and leaders, this documen..."
2228,s2229,Movie,Father Soldier Son,"Leslye Davis, Catrin Einhorn",NaN,United States,"July 17, 2020",2020,R,100 min,Documentaries,After a single father is severely wounded in A...
2779,s2780,Movie,Crip Camp: A Disability Revolution,NaN,NaN,United States,"March 25, 2020",2020,R,108 min,Documentaries,A groundbreaking summer camp galvanizes a grou...
5116,s5117,Movie,Jeremiah Tower: The Last Magnificent,Lydia Tenaglia,"Jeremiah Tower, Anthony Bourdain, Mario Batali...","Mexico, United States","December 20, 2017",2016,R,103 min,Documentaries,This documentary profiles influential chef Jer...
5179,s5180,Movie,Jerry Seinfeld: Comedian,Christian Charles,"Jerry Seinfeld, Orny Adams, Colin Quinn, Bill ...",United States,"November 7, 2017",2002,R,81 min,Documentaries,Christian Charles's documentary follows establ...
5197,s5198,Movie,The B-Side: Elsa Dorfman's Portrait Photography,Errol Morris,Elsa Dorfman,United States,"October 31, 2017",2016,R,76 min,Documentaries,"Filmmaker Errol Morris probes the life, work a..."
6104,s6105,Movie,Ai Weiwei: Never Sorry,Alison Klayman,"Ai Weiwei, Lao Ai",United States,"March 1, 2018",2012,R,91 min,Documentaries,Chinese artist and activist Ai Weiwei uses soc...
6545,s6546,Movie,Cutie and the Boxer,Zachary Heinzerling,"Noriko Shinohara, Ushio Shinohara",United States,"June 14, 2018",2013,R,82 min,Documentaries,A 2014 Oscar nominee for Best Documentary Feat...
6575,s6576,Movie,De Palma,"Noah Baumbach, Jake Paltrow",Brian De Palma,United States,"November 21, 2018",2015,R,110 min,Documentaries,Iconoclastic film director Brian DePalma takes...
6799,s6800,Movie,Freeway: Crack in the System,Marc Levin,Freeway Rick Ross,"United States, Nicaragua","December 15, 2017",2015,R,103 min,Documentaries,"Take in the true account of drug kingpin ""Free..."
7251,s7252,Movie,LA 92,"Daniel Lindsay, T.J. Martin",NaN,United States,"March 1, 2018",2017,R,114 min,Documentaries,Previously unseen footage is shaped into a fre...
8502,s8503,Movie,The Seven Five,Tiller Russell,NaN,United States,"April 14, 2017",2014,R,104 min,Documentaries,This riveting film examines the case of Mike D...

In [95]:
# fatch all movies of Ruben Fleischer
data[(data["type"] == "Movie") & (data["director"] == "Ruben Fleischer")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
6012,s6013,Movie,30 Minutes or Less,Ruben Fleischer,"Jesse Eisenberg, Danny McBride, Aziz Ansari, N...",United States,"January 1, 2021",2011,R,83 min,"Action & Adventure, Comedies",Two crooks planning a bank heist wind up abduc...
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...

In [100]:
# fatch the movie of Rajiv Chilaka
data[(data["type"] == "Movie") & (data["director"] == "Rajiv Chilaka")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
406,s407,Movie,Chhota Bheem - Neeli Pahaadi,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2013,TV-Y7,64 min,Children & Family Movies,Things get spooky when Bheem and his buddies t...
407,s408,Movie,Chhota Bheem & Ganesh,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2009,TV-Y7,68 min,Children & Family Movies,Bheem and Lord Ganesha join forces to save Dho...
408,s409,Movie,Chhota Bheem & Krishna: Mayanagari,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2011,TV-Y7,67 min,Children & Family Movies,Young lord Krishna has fallen for demoness Maa...
409,s410,Movie,Chhota Bheem & Krishna: Pataliputra- City of t...,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2010,TV-Y7,66 min,Children & Family Movies,Krishna needs Bheem’s help: The ruined city of...
410,s411,Movie,Chhota Bheem And The Broken Amulet,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",India,"July 22, 2021",2013,TV-Y7,64 min,Children & Family Movies,When a stranger tries to steal an amulet from ...
411,s412,Movie,Chhota Bheem And The Crown of Valhalla,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2013,TV-Y7,64 min,Children & Family Movies,To save the kingdom of Valhalla from invasion ...
412,s413,Movie,Chhota Bheem and the Incan Adventure,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2013,TV-Y7,65 min,Children & Family Movies,"When Dholakpur’s princess is kidnapped, Bheem ..."
413,s414,Movie,Chhota Bheem and The ShiNobi Secret,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2013,TV-Y7,64 min,Children & Family Movies,After learning of a samurai village under thre...
414,s415,Movie,Chhota Bheem Aur Hanuman,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2012,TV-Y7,68 min,Children & Family Movies,When two evil entities kidnap a princess in a ...
415,s416,Movie,Chhota Bheem aur Krishna,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",India,"July 22, 2021",2009,TV-Y7,68 min,Children & Family Movies,"Centuries after the end of a conqueror's rule,..."
416,s417,Movie,Chhota Bheem aur Krishna vs Zimbara,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2013,TV-Y7,64 min,Children & Family Movies,A demon of darkness is plotting world dominati...
419,s420,Movie,Chhota Bheem: Bheem vs Aliens,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2010,TV-Y7,69 min,"Children & Family Movies, Sports Movies",Space invaders have kidnapped Dholakpur’s king...
420,s421,Movie,Chhota Bheem: Dholakpur to Kathmandu,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2012,TV-Y7,70 min,Children & Family Movies,Bheem’s holiday in Nepal takes an unexpected t...
422,s423,Movie,Chhota Bheem: Journey to Petra,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2011,TV-Y7,68 min,Children & Family Movies,"The king has been away to meet an old friend, ..."
423,s424,Movie,Chhota Bheem: Master of Shaolin,Rajiv Chilaka,"Pooja Punabi, Mausam, Julie Tejwani, Rupa Bhim...",NaN,"July 22, 2021",2011,TV-Y7,74 min,Children & Family Movies,Summoned by a monk to help reclaim a temple fr...
424,s425,Movie,Chhota Bheem: The Rise of Kirmada,Rajiv Chilaka,"Vatsal Dubey, Julie Tejwani, Rupa Bhimani, Jig...",NaN,"July 22, 2021",2012,TV-Y7,68 min,Children & Family Movies,Bheem and young lord Krishna team up to protec...
2717,s2718,Movie,Chhota Bheem and the Curse of Damyaan,Rajiv Chilaka,"Kaustav Ghosh, Jigna Bhardwaj, Chutki, Rajesh ...",India,"April 1, 2020",2012,TV-Y7,87 min,Children & Family Movies,An evil demon who traded his freedom for immor...
6297,s6298,Movie,Bheemayan,Rajiv Chilaka,NaN,NaN,"May 10, 2019",2018,TV-Y,63 min,Children & Family Movies,"It's Diwali! To celebrate, Chhota Bheem and hi..."
6645,s6646,Movie,Dragonkala Ka Rahasya,Rajiv Chilaka,NaN,NaN,"June 18, 2019",2018,TV-Y,68 min,Children & Family Movies,Bheem helps to reopen Dragonpur's abandoned ma...

In [101]:
# cast David Attenborough in which movie
data[(data["type"] == "Movie") & (data["cast"] == "David Attenborough")]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1886,s1887,Movie,David Attenborough: A Life on Our Planet,"Alastair Fothergill, Jonnie Hughes, Keith Scholey",David Attenborough,"United States, United Kingdom","October 4, 2020",2020,PG,84 min,Documentaries,"A broadcaster recounts his life, and the evolu..."
3573,s3574,Movie,Our Planet - Behind The Scenes,NaN,David Attenborough,United Kingdom,"August 20, 2019",2019,TV-G,63 min,Documentaries,Years spent recording footage of creatures fro...
6811,s6812,Movie,Frozen Planet: On Thin Ice,NaN,David Attenborough,"United Kingdom, United States, Spain, Germany,...","January 28, 2016",2011,TV-PG,47 min,Movies,David Attenborough journeys to both polar regi...
6812,s6813,Movie,Frozen Planet: The Epic Journey,NaN,David Attenborough,"United Kingdom, United States, Spain, Germany,...","January 28, 2016",2011,TV-PG,52 min,Movies,Collecting highlights from the epic documentar...
7570,s7571,Movie,Nature: Raising the Dinosaur Giant,NaN,David Attenborough,United States,"March 1, 2017",2016,TV-G,53 min,Documentaries,Sir David Attenborough examines a recently dis...

In [110]:
data["title"] = data["title"].apply(lambda x: x.replace(" ",""))

In [111]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,DickJohnsonIsDead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood&Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,JailbirdsNewOrleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,KotaFactory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [112]:
data["id"] = data["show_id"]

In [113]:
data.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,id
0,s1,Movie,DickJohnsonIsDead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",s1
1,s2,TV Show,Blood&Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",s2

In [114]:
data["movie_time"] = data["type"] + data["duration"]

In [117]:
data.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,id,movie_time
0,s1,Movie,DickJohnsonIsDead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",s1,Movie90 min
1,s2,TV Show,Blood&Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",s2,TV Show2 Seasons

In [120]:
data.drop("movie_time",axis=1,inplace=True)

In [121]:
data.drop("id",axis=1,inplace=True)

In [122]:
data.head(2)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,DickJohnsonIsDead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood&Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."

In [126]:
data.drop(1)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,DickJohnsonIsDead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,JailbirdsNewOrleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,KotaFactory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,MidnightMass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,ZombieDumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [127]:
data.iloc[1]

show_id                                                        s2
type                                                      TV Show
title                                                 Blood&Water
director                                                      NaN
cast            Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
country                                              South Africa
date_added                                     September 24, 2021
release_year                                                 2021
rating                                                      TV-MA
duration                                                2 Seasons
listed_in         International TV Shows, TV Dramas, TV Mysteries
description     After crossing paths at a party, a Cape Town t...
Name: 1, dtype: object

In [130]:
data.loc[1]

show_id                                                        s2
type                                                      TV Show
title                                                 Blood&Water
director                                                      NaN
cast            Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
country                                              South Africa
date_added                                     September 24, 2021
release_year                                                 2021
rating                                                      TV-MA
duration                                                2 Seasons
listed_in         International TV Shows, TV Dramas, TV Mysteries
description     After crossing paths at a party, a Cape Town t...
Name: 1, dtype: object

In [132]:
data.loc[8000:8002]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8000,s8001,Movie,SheDidThat,NaN,"Luvvie Ajayi, Renae Bluitt, Melissa Butler, Li...",United States,"February 4, 2020",2019,TV-PG,71 min,Documentaries,"Go inside the lives of extraordinary, black fe..."
8001,s8002,Movie,Shelter,"Måns Mårlind, Björn Stein","Julianne Moore, Jonathan Rhys Meyers, Jeffrey ...",United States,"December 29, 2017",2010,R,112 min,"Horror Movies, Thrillers",A forensic psychiatrist has to think outside t...
8002,s8003,TV Show,Sherlock,NaN,"Benedict Cumberbatch, Martin Freeman, Una Stub...","United Kingdom, United States","May 15, 2017",2017,TV-14,4 Seasons,"British TV Shows, Crime TV Shows, Internationa...",In this updated take on Sir Arthur Conan Doyle...

In [133]:
data.loc[8000:8002,["title","cast"]]

           title                                               cast
8000  SheDidThat  Luvvie Ajayi, Renae Bluitt, Melissa Butler, Li...
8001     Shelter  Julianne Moore, Jonathan Rhys Meyers, Jeffrey ...
8002    Sherlock  Benedict Cumberbatch, Martin Freeman, Una Stub...

In [134]:
data.loc[[1,5],["title","cast"]]

          title                                               cast
1   Blood&Water  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
5  MidnightMass  Kate Siegel, Zach Gilford, Hamish Linklater, H...

In [136]:
data.iloc[1:5,[3,4]]

          director                                               cast
1              NaN  Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...
2  Julien Leclercq  Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...
3              NaN                                                NaN
4              NaN  Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...

In [143]:
data.iloc[[10,8000],[2,1]]

                               title     type
10    Vendetta:Truth,LiesandTheMafia  TV Show
8000                      SheDidThat    Movie

In [144]:
data.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,DickJohnsonIsDead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood&Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,JailbirdsNewOrleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,KotaFactory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [145]:
list(data.columns)

['show_id',
 'type',
 'title',
 'director',
 'cast',
 'country',
 'date_added',
 'release_year',
 'rating',
 'duration',
 'listed_in',
 'description']

In [151]:
df = data.loc[1:20,['director','cast','country','release_year']]

In [152]:
df

,director,cast,country,release_year
1,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021
2,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,2021
3,NaN,NaN,NaN,2021
4,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021
5,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,2021
6,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",NaN,2021
7,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",1993
8,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021
9,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021
10,NaN,NaN,NaN,2021
11,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",NaN,2021
12,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021
13,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",NaN,2021
14,NaN,NaN,NaN,2021
15,NaN,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,2021
16,"Pedro de Echave García, Pablo Azorín Williams",NaN,NaN,2020
17,NaN,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,2020
18,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",NaN,2021
19,NaN,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",NaN,2021
20,Olivier Megaton,NaN,NaN,2021

In [153]:
df.dropna(axis=1)

    release_year
1           2021
2           2021
3           2021
4           2021
5           2021
6           2021
7           1993
8           2021
9           2021
10          2021
11          2021
12          2021
13          2021
14          2021
15          2021
16          2020
17          2020
18          2021
19          2021
20          2021

In [155]:
df.dropna(axis=0)

,director,cast,country,release_year
7,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",1993
8,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021
9,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021
12,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021

In [161]:
df.fillna(147)

,director,cast,country,release_year
1,147,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021
2,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",147,2021
3,147,147,147,2021
4,147,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021
5,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",147,2021
6,"Robert Cullen, José Luis Ucha","Vanessa Hudgens, Kimiko Glenn, James Marsden, ...",147,2021
7,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin...",1993
8,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,2021
9,Theodore Melfi,"Melissa McCarthy, Chris O'Dowd, Kevin Kline, T...",United States,2021
10,147,147,147,2021
11,Kongkiat Komesiri,"Sukollawat Kanarot, Sushar Manaying, Pavarit M...",147,2021
12,Christian Schwochow,"Luna Wedler, Jannis Niewöhner, Milan Peschel, ...","Germany, Czech Republic",2021
13,Bruno Garotti,"Klara Castanho, Lucca Picon, Júlia Gomes, Marc...",147,2021
14,147,147,147,2021
15,147,"Logan Browning, Brandon P. Bell, DeRon Horton,...",United States,2021
16,"Pedro de Echave García, Pablo Azorín Williams",147,147,2020
17,147,"Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico,2020
18,Adam Salky,"Freida Pinto, Logan Marshall-Green, Robert Joh...",147,2021
19,147,"Blanca Suárez, Iván Marcos, Óscar Casas, Adriá...",147,2021
20,Olivier Megaton,147,147,2021

In [167]:
df.groupby("release_year").sum()

,director,cast,country
release_year,,,
1993,Haile Gerima,"Kofi Ghanaba, Oyafunmike Ogunlano, Alexandra D...","United States, Ghana, Burkina Faso, United Kin..."
2020,"Pedro de Echave García, Pablo Azorín Williams","Luis Ernesto Franco, Camila Sodi, Sergio Goyri...",Mexico
2021,"Julien LeclercqMike FlanaganRobert Cullen, Jos...","Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South AfricaIndiaUnited KingdomUnited StatesGe...